### ISSUE TITLE
Group sharing and permissions

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/AVIDWeb#118]
We need a way to allow groups to share editable sites between each other. We can have students join a group for a specific period and they would be allowed to add and edit data but then we need a way to remove them from the group without removing their data. Perhaps add a way to lock accounts?

**Comment by almasaeed2010** [comment]
There are already columns in the group_user table that allows you to specify who is a leader and who can view/edit. I believe they are called is_leader and can_view. We can add can_edit to it as well. Then we can allow the leaders of groups to control those variables.

**Comment by almasaeed2010** [comment]
Let's merge the PR for the demo now but I'd suggest we change the permissions modal to show the name of the user being modified. We can show it either on the modal's title or for each permission: `Allow Joe to view sites`

**Comment by jwest60** [comment]
In addition to the change described above, the checkboxes should be switched over to radio buttons since it doesn't make sense for a user to have editing permissions but not have permission to view. Maybe something like
- Disallow user to view or edit
- Allow user to view only
- Allow user to view and edit

**Comment by almasaeed2010** [comment]
Merged.
