### ISSUE TITLE
Pages need to be transferred

### ISSUE THREAD

**Issue by jwest60** [statonlab/AVIDWeb#159]
Pages that need to be added:
#### About
- [x] [About](http://aviddeer.com/about)
- [x] [Benefits of Using AVID](http://aviddeer.com/about/benefits-of-using-avid)
- [x] [Who We Are](http://aviddeer.com/about/who-we-are)
#### Deer Impacts
- [x] [Deer Impacts](http://aviddeer.com/deer-impacts)
- [x] [Woodland Conditions](http://aviddeer.com/deer-impacts/woodland-conditions)
- [x] [Signs and Symptoms](http://aviddeer.com/deer-impacts/signs-and-symptoms)
- [x] [Forest Health Effects](http://aviddeer.com/deer-impacts/forest-health-effects) (Same as Deer Impacts)
#### Site Preparation
- [x] [Site Selection](http://aviddeer.com/site-preparation/selecting-a-property)
- [x] [Key](http://aviddeer.com/site-preparation/key-to-aid-in-site-selection)
- [x] [Equipment](http://aviddeer.com/site-preparation/equipment-needed)
- [x] [Plots](http://aviddeer.com/site-preparation/set-up-sampling-plots)
- [x] [Quadrants](http://aviddeer.com/site-preparation/set-up-sampling-quadrants)
- [x] [Data](http://aviddeer.com/site-preparation/collecting-data)
#### User Guides
- [x] [Getting Started](http://aviddeer.com/user-guides/getting-started)
- [x] [Spring Wildflowers](http://aviddeer.com/user-guides/spring-wildflowers)
- [x] [Woody Seedlings](http://aviddeer.com/user-guides/woody-seedlings)
- [x] [Exclosures](http://aviddeer.com/user-guides/exclosures)
#### Resources
- [x] [Data Sheets](http://aviddeer.com/resources/data-sheets)
- [x] [Identification](http://aviddeer.com/resources/identification)
- [x] [References](http://aviddeer.com/resources/references)
- [x] [Instruction Manual](http://aviddeer.com/resources/avid-instruction-manual)

**Comment by almasaeed2010** [comment]
A new structure was added to the User Guides pages. Can you go through the rest of the page and replicate the structure?

Mainly:
- [ ] for each section, use the new content_sidebar component to create a sidebar menu for each page in the section.
- [ ] Instead of `card-header` elements, add the page title inside the `.card-body` and give the `h1` element a single class of `mb-4`.
- [ ] For each page in the section, add the sidebar in `col-md-4` and the main content in `col-md-8`
- [ ] Finally, do not add `card` class to the `col` itself, create a card inside the `col` instead.

**Comment by jwest60** [comment]
Done. #165
