### ISSUE TITLE
Plots issue

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/AVIDWeb#402]
The St Lawrence site in the database still had plots with incorrect designation of protected/unprotected for plots 11-21. I was able to change 11-16 to no instead of yes, but try as I may I cannot change plots 17-21 to no. I have made numerous attempts. Any thoughts?

**Comment by noahcaldwell7** [comment]
This isn't a bug, the issue is that St. Lawrence plots 17-21 are from a prior version of the database that didn't require latitude and longitude, so to submit the Update Plot form they must add latitude and longitude.

We should create a popup notification indicating the missing fields, since the form is so long that users don't notice the errors near the top of the form.
